### ISSUE TITLE
Use interface to interact precompile instead of low call

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-bridge-sol#87]
https://github.com/darwinia-network/darwinia-bridge-sol/blob/1a9b67755e7f44f97a1c0545b59454a1b5f25f78/contracts/mapping-token/contracts/darwinia/Sub2SubMappingTokenFactory.sol#L63

**Comment by xiaoch05** [comment]
right now we cannot fix this issue because the dvm does not support calling precompile contract by interface. see https://github.com/darwinia-network/darwinia-common/issues/916
and we add interface of the precompile contract to tell developers how to use it. https://github.com/darwinia-network/darwinia-bridge-sol/pull/88
